# Generated by Django 3.0.5 on 2020-07-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0)),
                ('good_reads_book_id', models.IntegerField(default=0)),
                ('isbn', models.CharField(max_length=10)),
                ('isbn13', models.CharField(max_length=13)),
                ('authors', models.CharField(max_length=250)),
                ('pub_year', models.IntegerField(default=2020)),
                ('title', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=10)),
                ('average_rating', models.FloatField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('ratings_1', models.IntegerField(default=0)),
                ('ratings_2', models.IntegerField(default=0)),
                ('ratings_3', models.IntegerField(default=0)),
                ('ratings_4', models.IntegerField(default=0)),
                ('ratings_5', models.IntegerField(default=0)),
                ('image_url', models.URLField(max_length=500)),
                ('small_image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=75)),
                ('comment', models.CharField(max_length=400)),
            ],
        ),
    ]
