# Generated by Django 3.0.5 on 2020-07-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksguru', '0002_auto_20200716_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
