# Generated by Django 3.0.5 on 2020-07-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksguru', '0005_auto_20200717_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='New comment...', max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Guest', max_length=75),
        ),
    ]
